# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title

# Setup
title:            'Living life and Make it Better'
tagline:          'life, learn, contribute'
description:      'learns software development, java programming, android, linux, and other open source technology'
url:              http://mic175i.github.io

author:
  name:           Endy Muhardin
  email:          endy.muhardin@gmail.com
  github:         endymuhardin
  twitter:        endymuhardin
  linkedin:       endy-muhardin
  facebook:       endy.muhardin
  url:            http://mic175i.github.io
  #email_md5:      a3c8a6a973fc0c0fa3d89cb69c103ad0#
  bio:            Software Developer berdomisili di Jabodetabek, berkutat di lingkungan open source, terutama Java dan Linux.

paginate:         5
